"""update_resume_table

Revision ID: b7650e545bee
Revises: 25ec941beec2
Create Date: 2026-06-05 04:04:17.890885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7650e545bee'
down_revision: Union[str, Sequence[str], None] = '25ec941beec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('resumes', 'parsed_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'parsed_content')
    # ### end Alembic commands ###
